import { Component, OnInit } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { MatSnackBar } from '@angular/material/snack-bar';
import { environment } from '../../environments/environment';

@Component({
  selector: 'app-letters-certificates',
  template: `
    <div class="page-container page-enter">
      <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:24px;">
        <div>
          <h1 class="page-title">Letters &amp; Certificates</h1>
          <p style="color:var(--text-3);font-size:13px;">Auto-generate HR letters and certificates</p>
        </div>
      </div>

      <div style="display:grid;grid-template-columns:1fr 1fr;gap:24px;">

        <!-- Left: Generator + History -->
        <div>
          <div class="card" style="margin-bottom:16px;">
            <h3 style="font-weight:700;margin-bottom:16px;">Generate Letter / Certificate</h3>
            <div style="display:flex;flex-direction:column;gap:12px;">
              <!-- Employee selector from API -->
              <select class="select" [(ngModel)]="gen.employeeId" (change)="onEmployeeChange()">
                <option value="">Select employee</option>
                <option *ngFor="let e of employees; trackBy: trackById" [value]="e.id">
                  {{e.firstName}} {{e.lastName}} ({{e.employeeCode || e.empId || '—'}})
                </option>
              </select>
              <select class="select" [(ngModel)]="gen.type" (change)="updateTemplate()">
                <option value="">Select letter type</option>
                <option *ngFor="let t of letterTypes; trackBy: trackByStr" [value]="t.id">{{t.label}}</option>
              </select>
              <input class="input" placeholder="Designation" [(ngModel)]="gen.designation">
              <input class="input" placeholder="Department" [(ngModel)]="gen.department">
              <input class="input" type="date" [(ngModel)]="gen.date" title="Letter date">
              <input class="input" *ngIf="gen.type"
                     placeholder="Additional info (e.g. salary, duration, new title)"
                     [(ngModel)]="gen.extra">
              <textarea class="textarea" style="height:60px;"
                        placeholder="Additional notes (optional)"
                        [(ngModel)]="gen.notes"></textarea>
              <div style="display:flex;gap:8px;">
                <button class="btn btn-primary"
                        (click)="generate()"
                        [disabled]="!gen.type || !gen.employeeId || saving">
                  {{saving ? 'Saving…' : 'Generate &amp; Save'}}
                </button>
                <button class="btn btn-ghost" (click)="reset()">Reset</button>
              </div>
            </div>
          </div>

          <!-- History -->
          <div class="card">
            <h3 style="font-weight:700;margin-bottom:12px;">Generated History</h3>
            <div *ngIf="loadingHistory" style="text-align:center;padding:24px;color:var(--text-3);">Loading…</div>
            <div class="hist-row" *ngFor="let h of history; trackBy: trackById">
              <div>
                <div style="font-weight:600;font-size:13px;">{{h.type}} — {{h.employee}}</div>
                <div style="font-size:11px;color:var(--text-3);">{{h.date}} · Generated by {{h.generatedBy || 'HR'}}</div>
              </div>
              <div style="display:flex;gap:6px;">
                <button class="btn btn-ghost btn-sm" (click)="previewHistory(h)">Preview</button>
                <button class="btn btn-primary btn-sm" (click)="downloadById(h.id)">Download PDF</button>
              </div>
            </div>
            <div *ngIf="!loadingHistory && history.length===0"
                 style="text-align:center;padding:24px;color:var(--text-3);font-size:13px;">
              No letters generated yet.
            </div>
          </div>
        </div>

        <!-- Right: Preview -->
        <div class="card letter-preview" *ngIf="preview">
          <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:16px;">
            <h3 style="font-weight:700;">Preview</h3>
            <div style="display:flex;gap:8px;">
              <button class="btn btn-primary btn-sm" (click)="download()">Download PDF</button>
              <button class="btn btn-ghost btn-sm" (click)="preview=null">✕</button>
            </div>
          </div>
          <div class="letter-paper">
            <div class="letter-header">
              <div style="font-size:20px;font-weight:900;color:#292966;">{{companyName}}</div>
              <div style="font-size:11px;color:#666;margin-top:2px;">{{companyAddress}}</div>
              <div style="height:2px;background:linear-gradient(90deg,#292966,#6b4df0);margin:10px 0;"></div>
            </div>
            <div style="font-size:13px;color:#333;margin-bottom:12px;">Date: {{preview.date}}</div>
            <div style="font-size:15px;font-weight:700;text-align:center;margin-bottom:16px;text-decoration:underline;">
              {{preview.title}}
            </div>
            <div style="font-size:13px;line-height:1.8;color:#333;" [innerHTML]="preview.body"></div>
            <div style="margin-top:32px;">
              <div style="font-size:13px;font-weight:700;">Authorised Signatory</div>
              <div style="font-size:12px;color:#666;margin-top:4px;">HR Department</div>
              <div style="font-size:12px;color:#666;">{{companyName}}</div>
            </div>
          </div>
        </div>

        <div class="card" *ngIf="!preview"
             style="display:flex;align-items:center;justify-content:center;min-height:400px;color:var(--text-3);">
          <div style="text-align:center;">
            <mat-icon style="font-size:48px;display:block;margin-bottom:12px;">article</mat-icon>
            <div style="font-size:14px;">Select employee &amp; letter type to preview</div>
          </div>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .hist-row { display:flex;justify-content:space-between;align-items:center;padding:10px 0;border-bottom:1px solid var(--border); }
    .hist-row:last-child { border-bottom:none; }
    .letter-preview { overflow-y:auto;max-height:80vh; }
    .letter-paper { background:#fff;border:1px solid #e5e7eb;border-radius:8px;padding:32px;font-family:'Times New Roman',serif; }
    .letter-header { margin-bottom:20px; }
    .textarea { width:100%;border:1px solid var(--border);border-radius:8px;padding:10px 12px;font-size:14px;resize:vertical;background:var(--surface);color:var(--text-1); }
  `]
})
export class LettersCertificatesComponent implements OnInit {
  private api = `${environment.apiUrl}/api/employees`;
  private settingsApi = `${environment.apiUrl}/api/settings`;

  saving = false;
  loadingHistory = false;
  preview: any = null;

  companyName = 'Your Company';
  companyAddress = '';

  employees: any[] = [];
  history: any[] = [];

  letterTypes = [
    { id: 'offer',       label: 'Offer Letter' },
    { id: 'appointment', label: 'Appointment Letter' },
    { id: 'experience',  label: 'Experience Certificate' },
    { id: 'salary',      label: 'Salary Certificate' },
    { id: 'relieving',   label: 'Relieving Letter' },
    { id: 'promotion',   label: 'Promotion Letter' },
    { id: 'noc',         label: 'NOC' },
    { id: 'bonafide',    label: 'Bonafide Certificate' },
    { id: 'increment',   label: 'Increment Letter' },
    { id: 'reference',   label: 'Reference Letter' },
  ];

  gen: any = {
    employeeId: '', employeeName: '', empCode: '',
    type: '', designation: '', department: '',
    date: new Date().toISOString().slice(0, 10),
    extra: '', notes: ''
  };

  trackById  = (_: number, item: any) => item.id;
  trackByStr = (_: number, s: string) => s;

  constructor(private http: HttpClient, private snack: MatSnackBar) {}

  ngOnInit() {
    this.loadCompanyInfo();
    this.loadEmployees();
    this.loadHistory();
  }

  loadCompanyInfo() {
    this.http.get<any>(`${this.settingsApi}/company`).subscribe({
      next: r => {
        const d = r?.data || r;
        this.companyName    = d?.companyName    || d?.name    || 'Your Company';
        this.companyAddress = d?.address || d?.companyAddress || '';
      },
      error: () => {}
    });
  }

  loadEmployees() {
    this.http.get<any>(`${environment.apiUrl}/api/employees`).subscribe({
      next: r => { this.employees = [...(r?.data || r || [])]; },
      error: () => {}
    });
  }

  loadHistory() {
    this.loadingHistory = true;
    this.http.get<any>(`${this.api}/letters`).subscribe({
      next: r => {
        const data = r?.data || r || [];
        this.history = [...data.map((h: any) => ({
          id: h.id,
          type:        h.letterType || h.type || '',
          employee:    h.employeeName || h.employee || '',
          empCode:     h.employeeCode || h.empCode || '',
          date:        h.generatedDate?.slice(0, 10) || h.date?.slice(0, 10) || '',
          generatedBy: h.generatedByName || h.generatedBy || ''
        }))];
        this.loadingHistory = false;
      },
      error: () => { this.loadingHistory = false; }
    });
  }

  onEmployeeChange() {
    const emp = this.employees.find(e => e.id === this.gen.employeeId);
    if (emp) {
      this.gen.employeeName = `${emp.firstName || ''} ${emp.lastName || ''}`.trim();
      this.gen.empCode      = emp.employeeCode || emp.empId || '';
      this.gen.designation  = this.gen.designation || emp.designation || '';
      this.gen.department   = this.gen.department  || emp.department  || '';
    }
  }

  updateTemplate() {}

  generate() {
    if (!this.gen.type || !this.gen.employeeId) return;
    const t = this.letterTypes.find(x => x.id === this.gen.type);
    const body = this.buildBody();
    this.preview = { title: t?.label, date: this.gen.date, body, id: null };

    const payload = {
      letterType:   t?.label,
      employeeId:   this.gen.employeeId,
      employeeName: this.gen.employeeName,
      employeeCode: this.gen.empCode,
      designation:  this.gen.designation,
      department:   this.gen.department,
      generatedDate: this.gen.date,
      additionalInfo: this.gen.extra,
      notes: this.gen.notes
    };

    this.saving = true;
    this.http.post<any>(`${this.api}/letters`, payload).subscribe({
      next: res => {
        this.preview.id = res?.data?.id || res?.id;
        this.saving = false;
        this.snack.open('Letter saved', '', { duration: 2000 });
        this.loadHistory();
      },
      error: () => {
        this.saving = false;
        this.snack.open('Letter generated (save failed — download still available)', 'Close', { duration: 4000 });
      }
    });
  }

  buildBody(): string {
    const { employeeName, empCode, designation, department, date, extra } = this.gen;
    const co = this.companyName;
    const bodies: Record<string, string> = {
      offer: `Dear <b>${employeeName}</b>,<br><br>We are pleased to extend you an offer of employment as <b>${designation}</b> in the <b>${department}</b> department at <b>${co}</b>, effective from <b>${date}</b>.<br><br>${extra ? `Your offered CTC is <b>${extra}</b>.` : ''}<br><br>Please sign and return the enclosed copy to confirm your acceptance.`,
      appointment: `Dear <b>${employeeName}</b>,<br><br>We are pleased to appoint you as <b>${designation}</b> in the <b>${department}</b> department at <b>${co}</b>, effective from <b>${date}</b>.<br><br>Your employment is subject to the terms and conditions detailed in your offer letter. We look forward to your valuable contribution.`,
      experience: `To Whom It May Concern,<br><br>This is to certify that <b>${employeeName}</b> (Employee ID: ${empCode}) has worked with <b>${co}</b> as <b>${designation}</b> in the <b>${department}</b> department.<br><br>${extra ? `Period of employment: <b>${extra}</b>.` : ''}<br><br>During the tenure, the employee demonstrated excellent professional skills and conduct. We wish them the very best in their future endeavours.`,
      salary: `To Whom It May Concern,<br><br>This is to certify that <b>${employeeName}</b> (Employee ID: ${empCode}) is working as <b>${designation}</b> at <b>${co}</b>.<br><br>${extra ? `The current CTC of the employee is <b>${extra}</b> per annum.` : ''}<br><br>This certificate is issued at the request of the employee for purposes stated by them.`,
      relieving: `Dear <b>${employeeName}</b>,<br><br>This is to confirm that you have been relieved from your duties as <b>${designation}</b> in the <b>${department}</b> department with effect from <b>${date}</b>.<br><br>Your full and final settlement is being processed. We appreciate your contributions during your tenure and wish you success in your future career.`,
      promotion: `Dear <b>${employeeName}</b>,<br><br>We are delighted to inform you that you have been promoted to the position of <b>${extra || designation}</b> effective from <b>${date}</b>.<br><br>This reflects our confidence in your abilities and the outstanding work you have consistently delivered. Congratulations on this well-deserved achievement.`,
      noc: `To Whom It May Concern,<br><br>This is to certify that <b>${employeeName}</b> (Employee ID: ${empCode}), <b>${designation}</b> at <b>${co}</b>, has no objection from the company for the purpose as stated by the employee.<br><br>This NOC is valid as of <b>${date}</b>.`,
      bonafide: `To Whom It May Concern,<br><br>This is to certify that <b>${employeeName}</b> (Employee ID: ${empCode}) is a bonafide employee of <b>${co}</b> working as <b>${designation}</b> in the <b>${department}</b> department.<br><br>This certificate is issued as requested for official purposes.`,
      increment: `Dear <b>${employeeName}</b>,<br><br>We are pleased to inform you that based on your performance and contribution, your salary has been revised ${extra ? `to <b>${extra}</b>` : ''} effective from <b>${date}</b>.<br><br>We appreciate your dedication and look forward to your continued contribution.`,
      reference: `To Whom It May Concern,<br><br>I am writing to provide a reference for <b>${employeeName}</b> who worked as <b>${designation}</b> in the <b>${department}</b> department at <b>${co}</b>.<br><br>${extra}<br><br>I recommend ${employeeName} without reservation and am confident they will be a valuable asset to any organisation.`,
    };
    return bodies[this.gen.type] || `This letter pertains to <b>${employeeName}</b> (${empCode}), ${designation}, ${department}. ${extra}`;
  }

  previewHistory(h: any) {
    const emp = this.employees.find(e => `${e.firstName} ${e.lastName}`.trim() === h.employee);
    if (emp) {
      this.gen.employeeId   = emp.id;
      this.gen.employeeName = h.employee;
      this.gen.empCode      = h.empCode;
      this.gen.designation  = emp.designation || '';
      this.gen.department   = emp.department  || '';
    } else {
      this.gen.employeeName = h.employee;
      this.gen.empCode      = h.empCode;
    }
    this.gen.type = this.letterTypes.find(t => t.label === h.type)?.id || '';
    this.gen.date = h.date;
    this.generate();
  }

  download() { if (this.preview?.id) this.downloadById(this.preview.id); }

  downloadById(id: any) {
    if (!id) { this.snack.open('No saved letter to download', 'Close', { duration: 3000 }); return; }
    this.http.get(`${this.api}/letters/${id}/download`, { responseType: 'blob' }).subscribe({
      next: blob => {
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `letter-${id}.pdf`;
        a.click();
        URL.revokeObjectURL(url);
      },
      error: () => this.snack.open('Download failed', 'Close', { duration: 3000 })
    });
  }

  reset() {
    this.gen = {
      employeeId: '', employeeName: '', empCode: '',
      type: '', designation: '', department: '',
      date: new Date().toISOString().slice(0, 10),
      extra: '', notes: ''
    };
    this.preview = null;
  }
}
